# NOTE: This is automatically generated code by desilike.bindings.cobaya.factory.CobayaLikelihoodGenerator
from desilike.bindings.cobaya.factory import CobayaLikelihoodFactory

from desilike.bindings.y1kp45_mock_challenge import AbacusSummitLRGFullPowerSpectrumMultipoles
AbacusSummitLRGFullPowerSpectrumMultipoles = CobayaLikelihoodFactory(AbacusSummitLRGFullPowerSpectrumMultipoles, __name__)

from desilike.bindings.y1kp45_mock_challenge import AbacusSummitLRGShapeFitPowerSpectrumMultipoles
AbacusSummitLRGShapeFitPowerSpectrumMultipoles = CobayaLikelihoodFactory(AbacusSummitLRGShapeFitPowerSpectrumMultipoles, __name__)

