# NOTE: This code has been automatically generated by desilike.bindings.cosmosis.factory.CosmoSISLikelihoodGenerator
from desilike.bindings.cosmosis.factory import CosmoSISLikelihoodFactory

from desilike.bindings.base import load_from_file
AbacusSummitLRGShapeFitPowerSpectrumMultipoles = load_from_file('/home/adematti/Bureau/DESI/NERSC/cosmodesi/desilike/desilike/bindings/y1kp45_mock_challenge/full_shape.py', 'AbacusSummitLRGShapeFitPowerSpectrumMultipoles')
AbacusSummitLRGShapeFitPowerSpectrumMultipoles = CosmoSISLikelihoodFactory(AbacusSummitLRGShapeFitPowerSpectrumMultipoles, {}, __name__)

setup, execute, cleanup = AbacusSummitLRGShapeFitPowerSpectrumMultipoles.build_module()

