# NOTE: This code has been automatically generated by desilike.bindings.cosmosis.factory.CosmoSISLikelihoodGenerator
from desilike.bindings.cosmosis.factory import CosmoSISLikelihoodFactory

from desilike.bindings.examples.y1kp45_mock_challenge.full_shape import AbacusSummitLRGDirectPowerSpectrumMultipoles
AbacusSummitLRGDirectPowerSpectrumMultipoles = CosmoSISLikelihoodFactory(AbacusSummitLRGDirectPowerSpectrumMultipoles, {}, __name__)

setup, execute, cleanup = AbacusSummitLRGDirectPowerSpectrumMultipoles.build_module()

