# NOTE: This code has been automatically generated by desilike.bindings.cosmosis.factory.CosmoSISLikelihoodGenerator
from desilike.bindings.cosmosis.factory import CosmoSISLikelihoodFactory

from desilike.bindings.examples.y1kp45_mock_challenge.full_shape import AbacusSummitLRGShapeFitPowerSpectrumMultipoles
AbacusSummitLRGShapeFitPowerSpectrumMultipoles = CosmoSISLikelihoodFactory(AbacusSummitLRGShapeFitPowerSpectrumMultipoles, {}, __name__)

setup, execute, cleanup = AbacusSummitLRGShapeFitPowerSpectrumMultipoles.build_module()

