# NOTE: This code has been automatically generated by desilike.bindings.montepython.factory.MontePythonLikelihoodGenerator
from desilike.bindings.montepython.factory import MontePythonLikelihoodFactory

from desilike.bindings.base import load_from_file
AbacusSummitLRGDirectPowerSpectrumMultipoles = load_from_file('/home/adematti/Bureau/DESI/NERSC/cosmodesi/desilike/desilike/bindings/y1kp45_mock_challenge/full_shape.py', 'AbacusSummitLRGDirectPowerSpectrumMultipoles')
AbacusSummitLRGDirectPowerSpectrumMultipoles = MontePythonLikelihoodFactory(AbacusSummitLRGDirectPowerSpectrumMultipoles, {}, __name__)

