# NOTE: This code has been automatically generated by desilike.bindings.cosmosis.factory.CosmoSISLikelihoodGenerator
from desilike.bindings.cosmosis.factory import CosmoSISLikelihoodFactory

from desilike.bindings.tests.test_generator import TestSimpleLikelihood
TestSimpleLikelihood = CosmoSISLikelihoodFactory(TestSimpleLikelihood, {}, __name__)

setup, execute, cleanup = TestSimpleLikelihood.build_module()

