# NOTE: This code has been automatically generated by desilike.bindings.cosmosis.factory.CosmoSISLikelihoodGenerator
from desilike.bindings.cosmosis.factory import CosmoSISLikelihoodFactory

from desilike.bindings.tests.test_generator import TestDirectKaiserLikelihood
TestDirectKaiserLikelihood = CosmoSISLikelihoodFactory(TestDirectKaiserLikelihood, TestDirectKaiserLikelihood, {}, __name__)

setup, execute, cleanup = TestDirectKaiserLikelihood.build_module()

