# NOTE: This is automatically generated code by desilike.bindings.cosmosis.factory.CosmoSISLikelihoodGenerator
from desilike.bindings.cosmosis.factory import CosmoSISLikelihoodFactory

from desilike.bindings.y1kp45_mock_challenge import AbacusSummitLRGShapeFitPowerSpectrumMultipoles
AbacusSummitLRGShapeFitPowerSpectrumMultipoles = CosmoSISLikelihoodFactory(AbacusSummitLRGShapeFitPowerSpectrumMultipoles, __name__)

setup, execute, cleanup = AbacusSummitLRGShapeFitPowerSpectrumMultipoles.build_module()

