# NOTE: This is automatically generated code by desilike.bindings.montepython.factory.MontePythonLikelihoodGenerator
from desilike.bindings.montepython.factory import MontePythonLikelihoodFactory

from desilike.bindings.y1kp45_mock_challenge import AbacusSummitLRGFullPowerSpectrumMultipoles
AbacusSummitLRGFullPowerSpectrumMultipoles = MontePythonLikelihoodFactory(AbacusSummitLRGFullPowerSpectrumMultipoles, __name__)

