import os
import sys

from desilike.parameter import ParameterCollection, Parameter
from desilike.utils import BaseClass, import_class, is_sequence


def find_module_from_file(fn):
    dirname = os.path.dirname(fn)
    if os.path.isfile(os.path.join(dirname, '__init__.py')):
        module = find_module_from_file(dirname) or os.path.basename(dirname)
        basename = os.path.splitext(os.path.basename(fn))[0]
        return '.'.join([module, basename])


def load_from_file(fn, obj):

    import importlib.util
    spec = importlib.util.spec_from_file_location('bindings', fn)
    foo = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(foo)
    return getattr(foo, obj)


class BaseLikelihoodGenerator(BaseClass):

    line_delimiter = '\n\n'

    def __init__(self, factory, dirname='.'):
        self.factory = factory
        self.header = '# NOTE: This code has been automatically generated by {}.{}\n'.format(self.__class__.__module__, self.__class__.__name__)
        self.header += 'from {} import {}'.format(self.factory.__module__, self.factory.__name__)
        self.dirname = os.path.abspath(os.path.join(dirname, os.path.basename(os.path.dirname(sys.modules[self.factory.__module__].__file__))))

    def get_code(self, likelihood, kw_like=None, module=None):
        self.kw_like = kw_like = kw_like or {}
        cls = import_class(likelihood)
        src_fn = sys.modules[cls.__module__].__file__
        src_dir = os.path.dirname(src_fn)
        fn = os.path.join(self.dirname, os.path.relpath(src_fn, os.path.commonpath([self.dirname, src_fn])))
        if module is None:
            module = find_module_from_file(src_fn)
        if module is not None:  # check if this is a package, then assumed in pythonpath
            code = 'from {} import {}\n'.format(module, cls.__name__)
        else:
            #code = 'import sys\n'
            #code += "sys.path.insert(0, '{}')\n".format(src_dir)
            #code += 'from {} import {}\n'.format(os.path.splitext(os.path.basename(fn))[0], cls.__name__)
            code = 'from desilike.bindings.base import load_from_file\n'
            code += "{} = load_from_file('{}', '{}')\n".format(cls.__name__, src_fn, cls.__name__)
        code += '{0} = {1}({0}, {2}, __name__)'.format(cls.__name__, self.factory.__name__, kw_like)
        return cls, fn, code

    def __call__(self, likelihood, module=None, kw_like=None):
        if not is_sequence(likelihood):
            likelihood = [likelihood]
        if not is_sequence(module):
            module = [module] * len(likelihood)
        if len(module) != len(likelihood):
            raise ValueError('Number of provided likelihood modules is not the same as the number of likelihoods')
        if not is_sequence(kw_like):
            kw_like = [kw_like] * len(likelihood)
        if len(kw_like) != len(likelihood):
            raise ValueError('Number of provided likelihood kwargs is not the same as the number of likelihoods')
        txt = {}
        for likelihood, kw_like, module in zip(likelihood, kw_like, module):
            fn, code = self.get_code(likelihood, kw_like, module=module)[1:]
            txt[fn] = txt.get(fn, []) + [code]
        for fn in txt:
            self.log_debug('Saving likelihood in {}'.format(fn))
            with open(fn, 'w') as file:
                file.write(self.header + self.line_delimiter)
                for line in txt[fn]:
                    file.write(line + self.line_delimiter)


def get_likelihood_params(likelihood):
    all_params = likelihood.runtime_info.pipeline.params.select(derived=False, solved=False)
    cosmo_names = likelihood.runtime_info.pipeline.get_cosmo_requires().get('params', {})
    cosmo_params, nuisance_params = ParameterCollection(), ParameterCollection()
    for param in all_params:
        if param.basename in cosmo_names:
            cosmo_params.set(param)
        else:
            nuisance_params.set(param)
    return cosmo_params, nuisance_params
