# NOTE: This code has been automatically generated by desilike.bindings.cobaya.factory.CobayaLikelihoodGenerator
from desilike.bindings.cobaya.factory import CobayaLikelihoodFactory

from desilike.bindings.base import load_from_file
AbacusSummitLRGDirectPowerSpectrumMultipoles = load_from_file('/home/adematti/Bureau/DESI/NERSC/cosmodesi/desilike/desilike/bindings/y1kp45_mock_challenge/full_shape.py', 'AbacusSummitLRGDirectPowerSpectrumMultipoles')
AbacusSummitLRGDirectPowerSpectrumMultipoles = CobayaLikelihoodFactory(AbacusSummitLRGDirectPowerSpectrumMultipoles, {}, __name__)

from desilike.bindings.base import load_from_file
AbacusSummitLRGShapeFitPowerSpectrumMultipoles = load_from_file('/home/adematti/Bureau/DESI/NERSC/cosmodesi/desilike/desilike/bindings/y1kp45_mock_challenge/full_shape.py', 'AbacusSummitLRGShapeFitPowerSpectrumMultipoles')
AbacusSummitLRGShapeFitPowerSpectrumMultipoles = CobayaLikelihoodFactory(AbacusSummitLRGShapeFitPowerSpectrumMultipoles, {}, __name__)

