# NOTE: This code has been automatically generated by desilike.bindings.cobaya.factory.CobayaLikelihoodGenerator
from desilike.bindings.cobaya.factory import CobayaLikelihoodFactory

from desilike.bindings.tests.test_generator import TestSimpleLikelihood
TestSimpleLikelihood = CobayaLikelihoodFactory(TestSimpleLikelihood, TestSimpleLikelihood, {}, __name__)

from desilike.bindings.tests.test_generator import TestShapeFitKaiserLikelihood
TestShapeFitKaiserLikelihood = CobayaLikelihoodFactory(TestShapeFitKaiserLikelihood, TestShapeFitKaiserLikelihood, {}, __name__)

from desilike.bindings.tests.test_generator import TestDirectKaiserLikelihood
TestDirectKaiserLikelihood = CobayaLikelihoodFactory(TestDirectKaiserLikelihood, TestDirectKaiserLikelihood, {}, __name__)

from desilike.bindings.tests.test_generator import TestEmulatedDirectKaiserLikelihood
TestEmulatedDirectKaiserLikelihood = CobayaLikelihoodFactory(TestEmulatedDirectKaiserLikelihood, TestEmulatedDirectKaiserLikelihood, {}, __name__)

