# NOTE: This code has been automatically generated by desilike.bindings.montepython.factory.MontePythonLikelihoodGenerator
from desilike.bindings.montepython.factory import MontePythonLikelihoodFactory

from desilike.bindings.tests.test_generator import TestDirectKaiserLikelihood
TestDirectKaiserLikelihood = MontePythonLikelihoodFactory(TestDirectKaiserLikelihood, TestDirectKaiserLikelihood, {}, __name__)

